export const ADMIN_CONSOLE_ENABLED = String(import.meta.env.VITE_ENABLE_ADMIN_CONSOLE || '').trim().toLowerCase() === 'true';

export const STRINGS = {
  title: 'CherryPick',
  subtitle: 'Pick carefully. One wrong answer and the round reward is gone.',
  homeTagline: 'A premium all-or-nothing quiz run built around fast solo boards, repeatable tension, and clean XP progression.',
  loadingTopics: 'Loading topics...',
  noTopics: 'No topics yet.',
  noTopicsHint: 'Import clean cards to populate topics and retry.',
  startRound: 'Start game',
  loadingCard: 'Loading round card...',
  retry: 'Retry',
  checkBackendUrl: 'Check backend URL:',
  openHealth: 'Open health',
  backendWarmupTitle: 'Waking up backend...',
  backendWarmupDetail: 'Render free instances can take a while to start. CherryPick is retrying automatically.',
  cardErrorFallback: 'Could not load card from backend. Retry to continue.',
  deckExhausted: 'No playable cards for this filter.',
  deckExhaustedHint: 'Change filters or restart game to continue.',
  changeFilters: 'Change filters',
  restartGame: 'Restart game',
  playersPlaceholder: 'Type player names and press Enter (or comma)',
  addPlayerHint: 'At least one player is required.',
  onboardingTitle: 'Set up your first quiz workspace',
  onboardingHint: 'Create a tenant + owner account context for this browser session.',
  onboardingWorkspaceLabel: 'Workspace name',
  onboardingWorkspacePlaceholder: 'Example: Northwind Quiz Night',
  onboardingEmailLabel: 'Owner email',
  onboardingEmailPlaceholder: 'owner@example.com',
  onboardingNameLabel: 'Display name (optional)',
  onboardingNamePlaceholder: 'Host name',
  onboardingSubmit: 'Create workspace',
  onboardingSubmitting: 'Creating workspace...',
  onboardingSuccess: 'Workspace ready. Tenant runtime context is now active.',
  signInTitle: 'Sign in to an existing host workspace',
  signInHint: 'Restore a host session without using internal headers.',
  signInEmailLabel: 'Host email',
  signInEmailPlaceholder: 'owner@example.com',
  signInTenantLabel: 'Tenant ID (optional)',
  signInTenantPlaceholder: 'Required only if your account belongs to multiple tenants',
  signInSubmit: 'Send sign-in link',
  signInSubmitting: 'Signing in...',
  signInSuccess: 'Host session restored.',
  launchPanelEyebrow: 'Narrow launch for recurring live quiz hosts',
  launchPanelTitle: 'Run branded recurring quiz nights without rebuilding the setup every week.',
  launchPanelHint: 'CherryPick is aimed at small professional hosts: community organizers, event operators, and recurring venue quiz nights.',
  launchPanelPrimaryCta: 'Start free host trial',
  launchPanelSecondaryCta: 'Sign in to existing workspace',
  launchPanelValueTitle: 'What the launch plan includes',
  launchPanelValue1: 'Branded host and player entry surfaces with one canonical create, join, replay, and duplicate-event flow.',
  launchPanelValue2: 'Host workspace with templates, recent session history, review, and replay tools built for repeat events.',
  launchPanelValue3: 'Runtime billing recovery, capability enforcement, and recurring-host support tracking already wired into the product.',
  launchPanelPricingTitle: 'Launch pricing',
  launchPanelPricingTrial: 'Trial',
  launchPanelPricingTrialDetail: 'Short evaluation path for first hosted runs and product fit checks.',
  launchPanelPricingPro: 'Pro Host',
  launchPanelPricingProDetail: 'Main paid plan for recurring hosts who need branding, analytics, templates, and larger live sessions.',
  launchPanelPricingTeam: 'Team/Agency later',
  launchPanelPricingTeamDetail: 'Reserved for multi-host collaboration after the solo recurring-host path is fully proven.',
  launchPanelAssuranceTitle: 'Launch assurances',
  launchPanelAssurance1: 'Hosted billing recovery path is built into the runtime.',
  launchPanelAssurance2: 'Recent host history, review, and duplicate launch are already first-class.',
  launchPanelAssurance3: 'Support and pilot evidence rails exist, even when launch proof is still below threshold.',
  signOutSubmit: 'Sign out',
  signOutSuccess: 'Signed out. Sign in again to restore tenant runtime.',
  sessionExpired: 'Host session expired or is invalid. Sign in again to restore tenant runtime.',
  upgradeSubmit: 'Upgrade to Pro',
  upgradeSubmitting: 'Starting checkout...',
  upgradeSuccessPrefix: 'Checkout initiated:',
  upgradeErrorFallback: 'Could not start checkout. Retry in a moment.',
  upgradeContinueSubmit: 'Continue to checkout',
  upgradeRecoverySubmit: 'Restore billing',
  upgradeRedirecting: 'Redirecting to checkout...',
  upgradeRecoveryHint: 'If checkout does not open automatically, continue with the billing link below.',
  billingReturnRefreshing: 'Billing return detected. Refreshing workspace entitlements...',
  billingReturnRestored: 'Billing restored. Paid capabilities are now active.',
  billingReturnPending: 'Billing return detected. Entitlements are still syncing; refresh again in a moment.',
  billingReturnCanceled: 'Checkout was canceled. Your current plan remains unchanged.',
  hostWorkspaceTitle: 'Host workspace',
  hostWorkspaceHint: 'Subscription state, recent host activity, and tenant usage live here.',
  hostWorkspaceLoading: 'Loading workspace insights...',
  hostWorkspaceNoActivity: 'No recent host activity yet.',
  hostWorkspaceNoUsage: 'No tracked tenant usage yet for this period.',
  hostWorkspaceAnalyticsLocked: 'Analytics and host history unlock on Pro Host. Upgrade to view recent activity and usage trends.',
  hostWorkspaceAnalyticsTitle: 'Host momentum',
  hostWorkspaceAnalyticsHint: 'A repeat-host snapshot from recent runs, roster size, and reusable templates.',
  hostWorkspaceAnalyticsRecentRuns: 'Recent runs',
  hostWorkspaceAnalyticsCompletedRuns: 'Completed runs',
  hostWorkspaceAnalyticsAverageRoster: 'Avg roster',
  hostWorkspaceAnalyticsSavedTemplates: 'Saved templates',
  hostWorkspaceAnalyticsFollowUpQueue: 'Follow-up queue',
  hostWorkspaceAnalyticsLiveRuns: 'Live runs',
  hostWorkspaceAnalyticsTopTopic: 'Top topic',
  hostWorkspaceAnalyticsLatestWinner: 'Latest winner',
  hostWorkspaceAnalyticsWinnerFallback: 'n/a',
  brandingEditorTitle: 'Branding',
  brandingEditorHint: 'Update the runtime app name, logo, and colors shown across host and player surfaces.',
  brandingLockedHint: 'Custom branding unlocks on Pro Host. Upgrade to apply your own app identity.',
  brandingRoleHint: 'Only owners and admins can update tenant branding.',
  brandingAppNameLabel: 'Brand app name',
  brandingLogoUrlLabel: 'Logo URL',
  brandingPrimaryColorLabel: 'Primary color',
  brandingSecondaryColorLabel: 'Secondary color',
  brandingSaveSubmit: 'Save branding',
  brandingSaving: 'Saving branding...',
  brandingSaved: 'Branding updated.',
  sessionTemplatesTitle: 'Session templates',
  sessionTemplatesHint: 'Save reusable host presets for recurring quiz events and relaunch them in one step.',
  sessionTemplatesLockedHint: 'Session templates unlock on Pro Host. Upgrade to save reusable event presets.',
  sessionTemplatesNameLabel: 'Template name',
  sessionTemplatesNamePlaceholder: 'Friday trivia default',
  sessionTemplatesSaveSubmit: 'Save current setup',
  sessionTemplatesSaving: 'Saving template...',
  sessionTemplatesSaved: 'Session template saved.',
  sessionTemplatesAppliedPrefix: 'Template applied:',
  sessionTemplatesDeleted: 'Session template deleted.',
  sessionTemplatesEmpty: 'No saved templates yet.',
  sessionTemplatesApplySubmit: 'Apply template',
  sessionTemplatesDeleteSubmit: 'Delete template',
  sessionTemplatesSaveFromHistorySubmit: 'Save as template',
  sessionTemplatesSavedFromHistoryPrefix: 'Session template saved from history:',
  hostedRuntimeBlocked: 'Hosted runtime is blocked until billing is restored. Upgrade or fix billing to launch sessions.',
  hostedRuntimePastDue: 'Billing is past due. Hosted launches are blocked until payment state is recovered.',
  hostedRuntimeCanceled: 'Subscription is canceled. Hosted launches are blocked until the tenant is upgraded again.',
  hostedPlayerCapPrefix: 'Hosted player cap:',
  hostedPlayerCapUpgrade: 'This plan allows fewer hosted players. Upgrade to launch larger sessions.',
  roomPanelTitle: 'Live room',
  roomPanelHint: 'Create the host room here, then share the code so players can join from the dedicated CherryPick join flow.',
  roomJoinLinkLabel: 'Player join link',
  roomDisplayNameLabel: 'Room display name',
  roomDisplayNamePlaceholder: 'Host or player name',
  roomCodeLabel: 'Room code',
  roomCodePlaceholder: 'ABC123',
  roomCreateSubmit: 'Create room',
  roomResumeSubmit: 'Resume room',
  roomClearSubmit: 'Clear saved room',
  roomPending: 'Working on room session...',
  roomCreatedPrefix: 'Room ready:',
  roomJoinedPrefix: 'Joined room:',
  roomResumedPrefix: 'Resumed room:',
  hostTopicRequired: 'Choose a topic before creating a host game.',
  hostStartTopicRequired: 'Choose a topic before starting the game.',
  hostRoomRequired: 'Create a host room before starting the game.',
  roomPlayerLobbyRefreshSubmit: 'Refresh lobby',
  roomPlayerLobbyLiveRefreshSubmit: 'Refresh game status',
  roomPlayerLobbyLeaveSubmit: 'Leave room',
  roomPlayersTitle: 'Players in room',
  roomNoPlayers: 'No players visible yet.',
  roomSavedHint: 'This room session is saved locally on this browser.',
  roomHostBadge: 'Host',
  roomPlayerBadge: 'Player',
  roomPlayerLobbyTitle: 'Player lobby',
  roomPlayerLobbyHint: 'Your browser is attached to this live room. Refresh to sync the roster, or leave before joining a different room code.',
  roomPlayerLobbyWaiting: 'You are checked into this room. The host will launch the live game when the roster is ready.',
  roomPlayerLobbyLive: 'This room is live. Joined devices follow the host-led session, and new joins are now closed.',
  roomPlayerLobbyRosterTitle: 'Live room roster',
  roomPlayerLobbySwitchHint: 'Leave this room before joining a different room code.',
  roomAlreadyLive: 'This room is already live.',
  playerRouteTitle: 'Join live room',
  playerRouteHint: 'Join the live room with your own display name, then follow the host-led CherryPick session from this device.',
  playerRouteDisplayNameLabel: 'Your display name',
  playerRouteJoinSubmit: 'Join room',
  playerRouteBackSubmit: 'Back to CherryPick',
  playerRouteLoading: 'Loading room preview...',
  playerRoutePreviewPlayersPrefix: 'Players waiting:',
  playerRoutePreviewMissing: 'Room preview is not available yet. You can still try joining directly.',
  playerRouteInvalid: 'Player join link is invalid.',
  roomUsePlayersSubmit: 'Use room players',
  roomUseSelectedPlayersSubmit: 'Use selected players',
  roomStartLiveSubmit: 'Start with room',
  roomStartSelectedLiveSubmit: 'Start selected room',
  roomSelectAllPlayersSubmit: 'Select all',
  roomSelectedRosterTitle: 'Selected for launch',
  roomSelectedRosterEmpty: 'Select at least one room player for the live setup.',
  roomSelectedRosterReadyPrefix: 'Selected room roster ready:',
  roomSelectedRosterStartPrefix: 'Starting room roster:',
  roomTrimSelectedPlayersSubmit: 'Trim to selected',
  roomTrimSelectedPlayersPrefix: 'Room trimmed to selected roster:',
  roomRemovePlayerSubmit: 'Remove',
  roomRemovePlayerPrefix: 'Removed room player:',
  roomUsePlayersMessage: 'Room players loaded into the live session setup.',
  recentHostedSessionsTitle: 'Recent hosted sessions',
  recentHostedSessionsEmpty: 'No hosted sessions launched yet.',
  recentHostedSessionPlayers: 'players',
  recentHostedSessionStatusLiveBadge: 'Live',
  recentHostedSessionStatusCompletedBadge: 'Completed',
  recentHostedSessionNoteBadge: 'Note saved',
  recentHostedSessionFilterAll: 'All',
  recentHostedSessionFilterLive: 'Live',
  recentHostedSessionFilterCompleted: 'Completed',
  recentHostedSessionFilterNotes: 'Needs follow-up',
  recentHostedSessionTopicFallback: 'Any topic',
  recentHostedSessionApplySubmit: 'Duplicate setup',
  recentHostedSessionReviewSubmit: 'Review session',
  recentHostedSessionResumeSubmit: 'Resume live',
  recentHostedSessionLaunchSubmit: 'Launch duplicate',
  recentHostedSessionRefreshSubmit: 'Refresh review',
  recentHostedSessionPreparedPrefix: 'Duplicate setup ready:',
  recentHostedSessionReviewPrefix: 'Reviewing session:',
  recentHostedSessionReviewReadyPrefix: 'Session review ready:',
  recentHostedSessionResumePrefix: 'Resuming live session:',
  recentHostedSessionLaunchPrefix: 'Launching duplicate session:',
  recentHostedSessionUseRoomRoster: 'Using saved room roster for the duplicate launch.',
  recentHostedSessionUseReviewedRoster: 'Using reviewed session roster for the duplicate launch.',
  recentHostedSessionUsePlaceholderRoster: 'Using placeholder player slots from the previous hosted session.',
  recentHostedSessionReviewTitle: 'Session review',
  recentHostedSessionReviewEmpty: 'Pick a recent hosted session to review its latest saved state.',
  recentHostedSessionReviewQuestionFallback: 'No saved round question is available for this session yet.',
  recentHostedSessionReviewLastActionFallback: 'No saved host action yet.',
  recentHostedSessionNotesTitle: 'Follow-up note',
  recentHostedSessionNotesPlaceholder: 'What should change before the next run?',
  recentHostedSessionNotesSaveSubmit: 'Save note',
  recentHostedSessionNotesClearSubmit: 'Clear note',
  recentHostedSessionNotesSaved: 'Follow-up note saved.',
  recentHostedSessionNotesCleared: 'Follow-up note cleared.',
  recentHostedSessionLeaderPrefix: 'Current leader:',
  recentHostedSessionStatusPrefix: 'Status:',
  recentHostedSessionStatusLive: 'Live',
  recentHostedSessionStatusCompleted: 'Completed',
  recentHostedSessionReviewError: 'Could not launch duplicate session from host history.',
  recentHostedSessionReviewLoadError: 'Could not load session review from host history.',
  adminConsoleDisabledTitle: 'Admin console unavailable',
  adminConsoleDisabledDetail: 'This public CherryPick deployment does not expose the internal admin console.',
  adminConsoleDisabledHint: 'Use the main game entry at / or enable the admin surface explicitly in an internal environment.'
};

export const CONFIG_STORAGE_KEY = 'smartiq.roundConfig';
export const ROOM_SESSION_STORAGE_KEY = 'smartiq.roomSession';
export const ROOM_SELECTION_STORAGE_PREFIX = 'smartiq.roomSelection.';
export const SESSION_REVIEW_NOTE_STORAGE_PREFIX = 'smartiq.sessionReviewNote.';

export const STARTUP_PHASE = {
  LOADING: 'loading',
  WARMING: 'warming',
  BACKEND_UNREACHABLE: 'backend-unreachable',
  CONTENT_UNHEALTHY: 'content-unhealthy',
  FORBIDDEN: 'forbidden',
  SERVER_ERROR: 'server-error',
  NOT_FOUND: 'not-found',
  TOPICS_EMPTY: 'topics-empty',
  READY: 'ready'
};

export const ENTRY_ROUTE = {
  HOME: 'home',
  PLAY: 'play',
  START: 'start',
  JOIN: 'join',
  HOST: 'host',
  HOST_TRIAL: 'host-trial',
  HOST_SIGNIN: 'host-signin'
};

export const SOLO_PLAYER_NAME = 'Solo Player';
export const SOLO_WIN_CONDITION = 1_000_000;
export const SHOW_BUILD_BADGE = import.meta.env.DEV
  || String(import.meta.env.VITE_SHOW_BUILD_BADGE || '').toLowerCase() === 'true';
export const BUILD_SHA = String(import.meta.env.VITE_BUILD_SHA || '').trim();

export const THEME_OPTIONS = [
  { value: 'classic', label: 'Classic' },
  { value: 'ember', label: 'Ember' },
  { value: 'ocean', label: 'Ocean' }
];
