name: Chore
description: Maintenance, tooling, docs, or refactor work.
title: "chore: "
labels: ["chore"]
body:
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What needs to be changed?
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: Why is this needed now?
    validations:
      required: true