create table if not exists game_history_entries
(
    id         bigint generated by default as identity primary key,
    game_id    varchar(128) not null,
    card_id    varchar(128) not null,
    category   varchar(32)  not null,
    topic      varchar(128),
    created_at timestamp with time zone not null default current_timestamp
);

create index if not exists idx_game_history_entries_game_id on game_history_entries (game_id);
create index if not exists idx_game_history_entries_game_id_id on game_history_entries (game_id, id);
