export const GamePhase = {
  SETUP: 'SETUP',
  LOADING_CARD: 'LOADING_CARD',
  CHOOSING: 'CHOOSING',
  CONFIRMING: 'CONFIRMING',
  RESOLVED: 'RESOLVED',
  PASSED: 'PASSED',
  ROUND_SUMMARY: 'ROUND_SUMMARY',
  GAME_OVER: 'GAME_OVER'
};

export const DEFAULT_PLAYERS = ['Player 1'];
export const DEFAULT_LANGS = ['en', 'et'];
